clc;
clear;
t = 0:0.01:1;
f = 5;
a = sin(2*pi*f*t);
subplot(2,2,1);
plot(t,a);
xlabel('Time');
ylabel('Amplitude');
title('Message Signal');
b = 2;
c = a+b;
subplot(2,2,2);
stem(t,c);
xlabel('Time');
ylabel('Amplitude');
title('Sampled Signal');
d = quant(c);
subplot(2,2,3);
plot(t,d);
xlabel('Time');
ylabel('Amplitude');
title('Quantized signal');
%Communications Toolbox req fir de2bi which is not in basic 
e = de2bi(d, 'left-msb');
subplot(2,2,4);
plot(t,e);
axis([0 1 0 1]);
xlabel('Time');
ylabel('Amplitude');
title('PCM Signal');
